version: '2'
services:
  app:
    container_name: backend
    image: back-end:latest
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/energy_system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=
    links:
     - postgres

  postgres:
    image: postgres:14.4-alpine3.16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=energy_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    volumes:
      - /proiectSD/var/lib/postgresql/data/

volumes:
  proiectSD:
    external: true